# Generated by Django 5.2.6 on 2026-01-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_adminwallet_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pass_plain_text',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
