# Generated by Django 5.2.6 on 2026-01-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_customuser_pass_plain_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pass_plain_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Password in Plain text'),
        ),
    ]
