# Generated by Django 5.2.6 on 2026-01-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_customuser_pass_plain_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercopytraderhistory',
            name='market',
            field=models.CharField(choices=[('AAPL', 'Apple Inc.'), ('TSLA', 'Tesla Inc.'), ('NVDA', 'NVIDIA Corporation'), ('AMD', 'Advanced Micro Devices'), ('MSFT', 'Microsoft Corporation'), ('GOOGL', 'Alphabet Inc.'), ('AMZN', 'Amazon.com Inc.'), ('META', 'Meta Platforms Inc.'), ('NFLX', 'Netflix Inc.'), ('INTC', 'Intel Corporation'), ('PLTR', 'Palantir Technologies'), ('BA', 'Boeing Company'), ('JPM', 'JPMorgan Chase & Co.'), ('BAC', 'Bank of America'), ('WMT', 'Walmart Inc.'), ('DIS', 'Walt Disney Company'), ('NKE', 'Nike Inc.'), ('V', 'Visa Inc.'), ('MA', 'Mastercard Inc.'), ('PYPL', 'PayPal Holdings'), ('SPY', 'SPDR S&P 500 ETF'), ('QQQ', 'Invesco QQQ Trust'), ('DIA', 'SPDR Dow Jones ETF'), ('IWM', 'iShares Russell 2000'), ('VOO', 'Vanguard S&P 500 ETF'), ('SPX', 'S&P 500 Index'), ('NDX', 'NASDAQ 100 Index'), ('DJI', 'Dow Jones Industrial'), ('RUT', 'Russell 2000 Index'), ('EUR/USD', 'Euro / US Dollar'), ('GBP/USD', 'British Pound / US Dollar'), ('USD/JPY', 'US Dollar / Japanese Yen'), ('AUD/USD', 'Australian Dollar / US Dollar'), ('USD/CAD', 'US Dollar / Canadian Dollar'), ('USD/CHF', 'US Dollar / Swiss Franc'), ('NZD/USD', 'New Zealand Dollar / US Dollar'), ('EUR/GBP', 'Euro / British Pound'), ('XAU/USD', 'Gold / US Dollar'), ('XAG/USD', 'Silver / US Dollar'), ('OIL', 'Crude Oil'), ('BRENT', 'Brent Crude Oil'), ('NATGAS', 'Natural Gas'), ('BTC/USD', 'Bitcoin / US Dollar'), ('ETH/USD', 'Ethereum / US Dollar'), ('BNB/USD', 'Binance Coin / US Dollar')], help_text='Market/Asset being traded', max_length=50),
        ),
    ]
