# Generated by Django 5.2.6 on 2026-01-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_usercopytraderhistory_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercopytraderhistory',
            name='leverage',
        ),
        migrations.AlterField(
            model_name='usercopytraderhistory',
            name='market',
            field=models.CharField(choices=[('AAPL', 'Apple Inc.'), ('TSLA', 'Tesla Inc.'), ('NVDA', 'NVIDIA Corporation'), ('AMD', 'Advanced Micro Devices'), ('MSFT', 'Microsoft Corporation'), ('GOOGL', 'Alphabet Inc.'), ('AMZN', 'Amazon.com Inc.'), ('META', 'Meta Platforms Inc.'), ('NFLX', 'Netflix Inc.'), ('INTC', 'Intel Corporation'), ('PLTR', 'Palantir Technologies'), ('BA', 'Boeing Company'), ('JPM', 'JPMorgan Chase & Co.'), ('BAC', 'Bank of America'), ('WMT', 'Walmart Inc.'), ('DIS', 'Walt Disney Company'), ('NKE', 'Nike Inc.'), ('V', 'Visa Inc.'), ('MA', 'Mastercard Inc.'), ('PYPL', 'PayPal Holdings'), ('SPY', 'SPDR S&P 500 ETF'), ('QQQ', 'Invesco QQQ Trust'), ('DIA', 'SPDR Dow Jones ETF'), ('IWM', 'iShares Russell 2000'), ('VOO', 'Vanguard S&P 500 ETF'), ('NDX', 'NASDAQ 100 Index'), ('DJI', 'Dow Jones Industrial'), ('RUT', 'Russell 2000 Index'), ('SPX', 'SPX Express')], help_text='Market/Asset being traded', max_length=50),
        ),
    ]
