# Generated by Django 5.2.6 on 2026-01-29 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_usercopytraderhistory_leverage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercopytraderhistory',
            options={'ordering': ['-opened_at'], 'verbose_name': 'Trader Trade History', 'verbose_name_plural': 'Trader Trade Histories'},
        ),
        migrations.RemoveIndex(
            model_name='usercopytraderhistory',
            name='app_usercop_user_id_4e972e_idx',
        ),
        migrations.RemoveField(
            model_name='usercopytraderhistory',
            name='profit_loss',
        ),
        migrations.RemoveField(
            model_name='usercopytraderhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertradercopy',
            name='minimum_amount_user_copied',
        ),
        migrations.AddField(
            model_name='usercopytraderhistory',
            name='profit_loss_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Profit or loss percentage', max_digits=10),
        ),
        migrations.AddField(
            model_name='usertradercopy',
            name='initial_investment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount user initially locked in with', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertradercopy',
            name='minimum_threshold_at_start',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Trader's minimum threshold when user started copying (for reference only)", max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercopytraderhistory',
            name='amount',
            field=models.DecimalField(decimal_places=8, help_text='Base amount invested', max_digits=20),
        ),
        migrations.AlterField(
            model_name='usercopytraderhistory',
            name='trader',
            field=models.ForeignKey(help_text='Trader who executed this trade', on_delete=django.db.models.deletion.CASCADE, related_name='trade_history', to='app.trader'),
        ),
        migrations.AlterField(
            model_name='usertradercopy',
            name='stopped_copying_at',
            field=models.DateTimeField(blank=True, help_text='When the user manually stopped copying (if applicable)', null=True),
        ),
    ]
