# Generated by Django 6.0.1 on 2026-02-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_usercopytraderhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='current_loyalty_status',
            field=models.CharField(choices=[('iron', 'Iron'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('elite', 'Elite')], default='iron', help_text='Current loyalty tier', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='next_loyalty_status',
            field=models.CharField(choices=[('iron', 'Iron'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('elite', 'Elite')], default='bronze', help_text='Next loyalty tier', max_length=20),
        ),
        migrations.AlterField(
            model_name='usertradercopy',
            name='initial_investment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount user initially locked in with', max_digits=12),
        ),
        migrations.AlterField(
            model_name='usertradercopy',
            name='minimum_threshold_at_start',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Trader's minimum threshold when user started copying (for reference only)", max_digits=12),
        ),
    ]
