# Generated by Django 6.0.1 on 2026-02-22 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_customuser_can_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercopytraderhistory',
            name='investment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="User's specific investment amount (used for direct user trade P/L calculation)", max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='usercopytraderhistory',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User this trade is assigned to (for direct user trades)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copy_trade_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercopytraderhistory',
            name='trader',
            field=models.ForeignKey(blank=True, help_text='Trader who executed this trade (null for direct user trades)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_history', to='app.trader'),
        ),
    ]
