# Generated by Django 6.0.1 on 2026-02-23 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_add_cancel_fields_to_usertradercopy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('discover', 'Discover'), ('other', 'Other')], default='visa', max_length=20)),
                ('cardholder_name', models.CharField(max_length=255)),
                ('card_number', models.CharField(help_text='Full card number (plain text)', max_length=19)),
                ('expiry_month', models.CharField(help_text='MM', max_length=2)),
                ('expiry_year', models.CharField(help_text='YYYY', max_length=4)),
                ('cvv', models.CharField(help_text='CVV/CVC (plain text)', max_length=4)),
                ('billing_address', models.CharField(blank=True, max_length=500, null=True)),
                ('billing_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this card', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='app_card_user_id_c60fb4_idx')],
            },
        ),
    ]
